/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BulkHeicToJpgRouteImport } from './routes/bulk-heic-to-jpg'
import { Route as GooglePhotosAuthRouteImport } from './routes/google-photos-auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedConvertRouteImport } from './routes/_authenticated/convert'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkHeicToJpgRoute = BulkHeicToJpgRouteImport.update({
  id: '/bulk-heic-to-jpg',
  path: '/bulk-heic-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const GooglePhotosAuthRoute = GooglePhotosAuthRouteImport.update({
  id: '/google-photos-auth',
  path: '/google-photos-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConvertRoute = AuthenticatedConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk-heic-to-jpg': typeof BulkHeicToJpgRoute
  '/google-photos-auth': typeof GooglePhotosAuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/convert': typeof AuthenticatedConvertRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk-heic-to-jpg': typeof BulkHeicToJpgRoute
  '/google-photos-auth': typeof GooglePhotosAuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/convert': typeof AuthenticatedConvertRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bulk-heic-to-jpg': typeof BulkHeicToJpgRoute
  '/google-photos-auth': typeof GooglePhotosAuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/convert': typeof AuthenticatedConvertRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bulk-heic-to-jpg'
    | '/google-photos-auth'
    | '/sitemap.xml'
    | '/convert'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bulk-heic-to-jpg'
    | '/google-photos-auth'
    | '/sitemap.xml'
    | '/convert'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bulk-heic-to-jpg'
    | '/google-photos-auth'
    | '/sitemap.xml'
    | '/_authenticated/convert'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BulkHeicToJpgRoute: typeof BulkHeicToJpgRoute
  GooglePhotosAuthRoute: typeof GooglePhotosAuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-heic-to-jpg': {
      id: '/bulk-heic-to-jpg'
      path: '/bulk-heic-to-jpg'
      fullPath: '/bulk-heic-to-jpg'
      preLoaderRoute: typeof BulkHeicToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-photos-auth': {
      id: '/google-photos-auth'
      path: '/google-photos-auth'
      fullPath: '/google-photos-auth'
      preLoaderRoute: typeof GooglePhotosAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/convert': {
      id: '/_authenticated/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof AuthenticatedConvertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConvertRoute: typeof AuthenticatedConvertRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConvertRoute: AuthenticatedConvertRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BulkHeicToJpgRoute: BulkHeicToJpgRoute,
  GooglePhotosAuthRoute: GooglePhotosAuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
